import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common';
import { BoqNode } from '@prisma/client';
import type { RequestIdentity } from '@erp/types';

import { TenancyService } from '../../../../platform/tenancy/tenancy.service.js';
import { BoqPrismaRepository, BoqWithVersions } from '../infrastructure/boq-prisma.repository.js';
import type { CreateNodeDto } from '../presentation/dto/create-node.dto.js';
import type { UpdateNodeDto } from '../presentation/dto/update-node.dto.js';
import type { MoveNodeDto } from '../presentation/dto/move-node.dto.js';

export interface BoqTreeNode extends BoqNode {
  children: BoqTreeNode[];
  computedTotal: number | null;
}

@Injectable()
export class BoqTreeService {
  constructor(
    private readonly tenancyService: TenancyService,
    private readonly repo: BoqPrismaRepository,
  ) {}

  // ─── Queries ─────────────────────────────────────────────────────────────────

  async getTree(
    identity: RequestIdentity,
    projectId: string,
    versionId: string,
  ): Promise<BoqTreeNode[]> {
    const prisma = this.tenancyService.getClient();
    const boq = await this.requireBoqForProject(prisma, projectId, identity.activeOrganizationId);
    await this.requireVersionBelongsToBoq(versionId, boq);

    const nodes = await this.repo.findNodesByVersion(prisma, versionId);
    return this.buildTree(nodes);
  }

  // ─── Commands ────────────────────────────────────────────────────────────────

  async addNode(
    identity: RequestIdentity,
    projectId: string,
    versionId: string,
    dto: CreateNodeDto,
  ): Promise<BoqNode> {
    const prisma = this.tenancyService.getClient();
    const boq = await this.requireBoqForProject(prisma, projectId, identity.activeOrganizationId);
    await this.requireVersionBelongsToBoq(versionId, boq);
    await this.requireDraftVersion(prisma, versionId);

    // Determine parent context
    let parentPath: string | null = null;
    let parentDepth = -1;

    if (dto.parentId) {
      const parent = await this.repo.findNodeById(prisma, dto.parentId);
      if (!parent || parent.versionId !== versionId) {
        throw new NotFoundException(`Parent node ${dto.parentId} not found in this version`);
      }
      if (parent.isLeaf) {
        throw new BadRequestException('Cannot add children to a leaf node');
      }
      parentPath = parent.path;
      parentDepth = parent.depth;
    }

    const totalAmount = this.computeLeafTotal(dto.quantity, dto.unitRate, dto.isLeaf);

    // The node ID is generated by Prisma's cuid() default — we use the returned record.
    const node = await this.repo.createNode(prisma, {
      boqId: boq.id,
      versionId,
      parentId: dto.parentId ?? null,
      path: '__placeholder__', // updated immediately below once we have the ID
      depth: parentDepth + 1,
      sortOrder: dto.sortOrder,
      code: dto.code,
      description: dto.description,
      descriptionAr: dto.descriptionAr ?? null,
      isLeaf: dto.isLeaf ?? false,
      unit: dto.unit ?? null,
      quantity: dto.quantity ?? null,
      unitRate: dto.unitRate ?? null,
      currency: dto.currency ?? null,
      totalAmount,
    });

    // Build the correct materialized path now that we have the node ID.
    const path = parentPath ? `${parentPath}/${node.id}` : node.id;
    return this.repo.updateNode(prisma, node.id, { path });
  }

  async updateNode(
    identity: RequestIdentity,
    projectId: string,
    versionId: string,
    nodeId: string,
    dto: UpdateNodeDto,
  ): Promise<BoqNode> {
    const prisma = this.tenancyService.getClient();
    const boq = await this.requireBoqForProject(prisma, projectId, identity.activeOrganizationId);
    await this.requireVersionBelongsToBoq(versionId, boq);
    await this.requireDraftVersion(prisma, versionId);

    const node = await this.requireNode(prisma, nodeId, versionId);

    // Prevent making a node a leaf if it has children
    if (dto.isLeaf === true) {
      const childCount = await this.repo.countChildren(prisma, nodeId, versionId);
      if (childCount > 0) {
        throw new BadRequestException('Cannot mark a node as a leaf — it has child nodes.');
      }
    }

    const isLeaf = dto.isLeaf ?? node.isLeaf;
    const quantity = dto.quantity !== undefined ? dto.quantity : (node.quantity ? Number(node.quantity) : undefined);
    const unitRate = dto.unitRate !== undefined ? dto.unitRate : (node.unitRate ? Number(node.unitRate) : undefined);
    const totalAmount = this.computeLeafTotal(quantity, unitRate, isLeaf);

    return this.repo.updateNode(prisma, nodeId, {
      code: dto.code,
      description: dto.description,
      descriptionAr: dto.descriptionAr,
      isLeaf,
      unit: dto.unit,
      quantity: dto.quantity,
      unitRate: dto.unitRate,
      currency: dto.currency,
      totalAmount,
    });
  }

  async moveNode(
    identity: RequestIdentity,
    projectId: string,
    versionId: string,
    nodeId: string,
    dto: MoveNodeDto,
  ): Promise<void> {
    const prisma = this.tenancyService.getClient();
    const boq = await this.requireBoqForProject(prisma, projectId, identity.activeOrganizationId);
    await this.requireVersionBelongsToBoq(versionId, boq);
    await this.requireDraftVersion(prisma, versionId);

    const node = await this.requireNode(prisma, nodeId, versionId);

    if (dto.newParentId === nodeId) {
      throw new BadRequestException('Cannot move a node to itself.');
    }

    // Detect circular move: the new parent cannot be a descendant of the moved node.
    if (dto.newParentId) {
      const newParent = await this.repo.findNodeById(prisma, dto.newParentId);
      if (!newParent || newParent.versionId !== versionId) {
        throw new NotFoundException(`Target parent node ${dto.newParentId} not found`);
      }
      if (newParent.isLeaf) {
        throw new BadRequestException('Cannot move a node under a leaf node.');
      }
      if (newParent.path.startsWith(node.path + '/') || newParent.path === node.path) {
        throw new BadRequestException('Cannot move a node to one of its own descendants.');
      }

      await this.repo.moveNode(
        prisma,
        versionId,
        node,
        dto.newParentId,
        newParent.path,
        newParent.depth,
        dto.newSortOrder,
      );
    } else {
      // Move to root
      await this.repo.moveNode(prisma, versionId, node, null, null, -1, dto.newSortOrder);
    }
  }

  async deleteNode(
    identity: RequestIdentity,
    projectId: string,
    versionId: string,
    nodeId: string,
  ): Promise<void> {
    const prisma = this.tenancyService.getClient();
    const boq = await this.requireBoqForProject(prisma, projectId, identity.activeOrganizationId);
    await this.requireVersionBelongsToBoq(versionId, boq);
    await this.requireDraftVersion(prisma, versionId);

    const node = await this.requireNode(prisma, nodeId, versionId);

    const childCount = await this.repo.countChildren(prisma, nodeId, versionId);
    if (childCount > 0) {
      throw new BadRequestException(
        'Cannot delete a node that has children. Delete or re-parent children first.',
      );
    }

    await this.repo.deleteNode(prisma, node.id);
  }

  // ─── Private helpers ──────────────────────────────────────────────────────────

  private async requireBoqForProject(
    prisma: ReturnType<TenancyService['getClient']>,
    projectId: string,
    organizationId: string,
  ): Promise<BoqWithVersions> {
    const boq = await this.repo.findByProject(prisma, projectId);
    if (!boq) throw new NotFoundException(`No BOQ found for project ${projectId}`);
    if (boq.organizationId !== organizationId) throw new ForbiddenException();
    return boq;
  }

  private requireVersionBelongsToBoq(versionId: string, boq: BoqWithVersions): void {
    const belongs = boq.versions.some((v) => v.id === versionId);
    if (!belongs) throw new NotFoundException(`Version ${versionId} does not belong to this BOQ`);
  }

  private async requireDraftVersion(
    prisma: ReturnType<TenancyService['getClient']>,
    versionId: string,
  ): Promise<void> {
    const version = await this.repo.findVersion(prisma, versionId);
    if (!version) throw new NotFoundException(`Version ${versionId} not found`);
    if (version.status !== 'DRAFT') {
      throw new ForbiddenException('BOQ nodes can only be modified in a DRAFT version.');
    }
  }

  private async requireNode(
    prisma: ReturnType<TenancyService['getClient']>,
    nodeId: string,
    versionId: string,
  ): Promise<BoqNode> {
    const node = await this.repo.findNodeById(prisma, nodeId);
    if (!node || node.versionId !== versionId) {
      throw new NotFoundException(`Node ${nodeId} not found in version ${versionId}`);
    }
    return node;
  }

  private computeLeafTotal(
    quantity: number | null | undefined,
    unitRate: number | null | undefined,
    isLeaf: boolean | null | undefined,
  ): number | null {
    if (!isLeaf || quantity == null || unitRate == null) return null;
    return Math.round(quantity * unitRate * 100) / 100;
  }

  /**
   * Converts a flat ordered list of nodes into a recursive tree.
   * Parent totals are computed bottom-up from leaf totalAmounts.
   */
  private buildTree(nodes: BoqNode[]): BoqTreeNode[] {
    const map = new Map<string, BoqTreeNode>();

    for (const node of nodes) {
      map.set(node.id, { ...node, children: [], computedTotal: node.totalAmount ? Number(node.totalAmount) : null });
    }

    const roots: BoqTreeNode[] = [];

    for (const treeNode of map.values()) {
      if (treeNode.parentId) {
        const parent = map.get(treeNode.parentId);
        if (parent) parent.children.push(treeNode);
      } else {
        roots.push(treeNode);
      }
    }

    // Bottom-up total computation for summary nodes
    this.sumTotals(roots);
    return roots;
  }

  private sumTotals(nodes: BoqTreeNode[]): number | null {
    let sum: number | null = null;
    for (const node of nodes) {
      if (node.children.length > 0) {
        const childSum = this.sumTotals(node.children);
        node.computedTotal = childSum;
      }
      if (node.computedTotal !== null) {
        sum = (sum ?? 0) + node.computedTotal;
      }
    }
    return sum;
  }
}
