export enum TenantStatus {
  PROVISIONING = 'PROVISIONING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
}

export enum Language {
  EN = 'EN',
  AR = 'AR',
}

export enum WorkflowTransactionType {
  MATERIAL_REQUEST = 'MATERIAL_REQUEST',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  SUPPLIER_PAYMENT = 'SUPPLIER_PAYMENT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  MATERIAL_ISSUE = 'MATERIAL_ISSUE',
  SUBCONTRACT_CERTIFICATE = 'SUBCONTRACT_CERTIFICATE',
  IPC = 'IPC',
  VARIATION = 'VARIATION',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ApprovalActionType {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  DELEGATE = 'DELEGATE',
  ESCALATE = 'ESCALATE',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum WorkflowTriggerKind {
  DOCUMENT = 'DOCUMENT',
  STATE_TRANSITION = 'STATE_TRANSITION',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  MOBILIZING = 'MOBILIZING',
  ACTIVE = 'ACTIVE',
  PRACTICAL_COMPLETION = 'PRACTICAL_COMPLETION',
  CLOSEOUT = 'CLOSEOUT',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ProjectRole {
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  QUANTITY_SURVEYOR = 'QUANTITY_SURVEYOR',
  SITE_ENGINEER = 'SITE_ENGINEER',
  COMMERCIAL_MANAGER = 'COMMERCIAL_MANAGER',
  FINANCE_REVIEWER = 'FINANCE_REVIEWER',
  VIEWER = 'VIEWER',
}

export enum BoqVersionStatus {
  DRAFT = 'DRAFT',
  BASELINED = 'BASELINED',
  SUPERSEDED = 'SUPERSEDED',
  CANCELLED = 'CANCELLED',
}
