export enum TenantStatus {
  PROVISIONING = 'PROVISIONING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
}

export enum Language {
  EN = 'EN',
  AR = 'AR',
}

export enum WorkflowTransactionType {
  MATERIAL_REQUEST = 'MATERIAL_REQUEST',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  SUPPLIER_PAYMENT = 'SUPPLIER_PAYMENT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  MATERIAL_ISSUE = 'MATERIAL_ISSUE',
  SUBCONTRACT_CERTIFICATE = 'SUBCONTRACT_CERTIFICATE',
  IPC = 'IPC',
  VARIATION = 'VARIATION',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ApprovalActionType {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  DELEGATE = 'DELEGATE',
  ESCALATE = 'ESCALATE',
}
