export enum TenantStatus {
  PROVISIONING = 'PROVISIONING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
}

export enum Language {
  EN = 'EN',
  AR = 'AR',
}

export enum WorkflowTransactionType {
  MATERIAL_REQUEST = 'MATERIAL_REQUEST',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  SUPPLIER_PAYMENT = 'SUPPLIER_PAYMENT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  MATERIAL_ISSUE = 'MATERIAL_ISSUE',
  SUBCONTRACT_CERTIFICATE = 'SUBCONTRACT_CERTIFICATE',
  IPC = 'IPC',
  VARIATION = 'VARIATION',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ApprovalActionType {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  DELEGATE = 'DELEGATE',
  ESCALATE = 'ESCALATE',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum WorkflowTriggerKind {
  DOCUMENT = 'DOCUMENT',
  STATE_TRANSITION = 'STATE_TRANSITION',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  MOBILIZING = 'MOBILIZING',
  ACTIVE = 'ACTIVE',
  PRACTICAL_COMPLETION = 'PRACTICAL_COMPLETION',
  CLOSEOUT = 'CLOSEOUT',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ProjectRole {
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  QUANTITY_SURVEYOR = 'QUANTITY_SURVEYOR',
  SITE_ENGINEER = 'SITE_ENGINEER',
  COMMERCIAL_MANAGER = 'COMMERCIAL_MANAGER',
  FINANCE_REVIEWER = 'FINANCE_REVIEWER',
  VIEWER = 'VIEWER',
}

export enum BoqVersionStatus {
  DRAFT = 'DRAFT',
  BASELINED = 'BASELINED',
  SUPERSEDED = 'SUPERSEDED',
  CANCELLED = 'CANCELLED',
}

export enum CommercialModel {
  CLIENT_CONTRACT = 'CLIENT_CONTRACT',
  INTERNAL_CAPITAL = 'INTERNAL_CAPITAL',
}

export enum ParticipationModel {
  SOLE = 'SOLE',
  JOINT_VENTURE = 'JOINT_VENTURE',
}

export enum MeasurementMethod {
  QUANTITY = 'QUANTITY',
  PERCENTAGE = 'PERCENTAGE',
  MILESTONE = 'MILESTONE',
}

export enum PricingBasis {
  UNIT_RATE = 'UNIT_RATE',
  LUMP_SUM = 'LUMP_SUM',
}

export enum WorkflowRequirement {
  REQUIRED = 'REQUIRED',
  OPTIONAL = 'OPTIONAL',
  NONE = 'NONE',
}

export enum ClientStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ContractStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  ACTIVE = 'ACTIVE',
  FINAL_ACCOUNT_PENDING = 'FINAL_ACCOUNT_PENDING',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  TERMINATED = 'TERMINATED',
}

export enum BillingModel {
  MEASURED_IPC = 'MEASURED_IPC',
  MILESTONE = 'MILESTONE',
  TIME_AND_MATERIAL = 'TIME_AND_MATERIAL',
  HYBRID = 'HYBRID',
}

export enum AdvanceType {
  MOBILIZATION = 'MOBILIZATION',
  MATERIAL_ON_SITE = 'MATERIAL_ON_SITE',
  EQUIPMENT = 'EQUIPMENT',
  OTHER = 'OTHER',
}

export enum GuaranteeStatus {
  ACTIVE = 'ACTIVE',
  DISCHARGED = 'DISCHARGED',
  EXPIRED = 'EXPIRED',
  CALLED = 'CALLED',
}

export enum IpaStatus {
  DRAFT = 'DRAFT',
  PENDING_INTERNAL_APPROVAL = 'PENDING_INTERNAL_APPROVAL',
  RETURNED_FOR_REVISION = 'RETURNED_FOR_REVISION',
  APPROVED_FOR_SUBMISSION = 'APPROVED_FOR_SUBMISSION',
  SUBMITTED = 'SUBMITTED',
  CANCELLED = 'CANCELLED',
}

export enum IpcStatus {
  CERTIFIED = 'CERTIFIED',
  PARTIALLY_CERTIFIED = 'PARTIALLY_CERTIFIED',
  REJECTED = 'REJECTED',
}
