/**
 * "Send by WhatsApp" for a client document (ADR-042 phase 2). One request/response shape for every
 * document that can be sent — receipt today (`/customer-receipts/:id/whatsapp`), invoice next — so
 * the web has one send dialog.
 */

/** Why a document cannot be sent right now (null when it can). */
export type WhatsAppSendBlockedReason =
  | 'NOT_POSTED'
  /** The document was posted and has since been reversed — it must not be sent. */
  | 'REVERSED'
  | 'NO_RECIPIENT'
  | 'TEMPLATE_NOT_CONFIGURED'
  | 'WHATSAPP_NOT_CONFIGURED';

/** One of the client's contacts the document could go to. */
export interface WhatsAppRecipientOption {
  contactId: string;
  name: string;
  role: string | null;
  /** E.164, e.g. '+252612345678'. */
  number: string;
  isPrimary: boolean;
  /** 'whatsapp' = the contact's WhatsApp number; 'phone' = their phone (no WhatsApp number on file). */
  source: 'whatsapp' | 'phone';
}

/** `GET …/whatsapp/preview` */
export interface WhatsAppSendPreview {
  /** The server has an approved template name set for this kind of document. */
  templateConfigured: boolean;
  /** The server has a WhatsApp connection (access token + phone number id). */
  whatsappConfigured: boolean;
  /** Primary contact first. */
  recipients: WhatsAppRecipientOption[];
  /** E.164 of the number used when the send request names none (the primary contact's), or null. */
  defaultRecipient: string | null;
  /** The message body exactly as the client will read it. */
  message: string;
  /** The attached PDF's file name, e.g. 'RCP-000017.pdf'. */
  filename: string;
  /** True when `blockedReason` is null. */
  sendable: boolean;
  blockedReason: WhatsAppSendBlockedReason | null;
}

/** `POST …/whatsapp` body. Response: `OutboundMessageView`. */
export interface WhatsAppSendRequest {
  /** E.164; omitted → `defaultRecipient`. Any valid number is accepted, not only a contact's. */
  recipient?: string;
  /**
   * Generated by the web once per send dialog (e.g. a UUID) and reused on a retry of the same send:
   * a repeat returns the same message instead of sending twice; a retry after FAILED re-sends.
   */
  idempotencyKey: string;
}
