import { Injectable } from '@nestjs/common';
import type { InputJsonValue } from '@prisma/client/runtime/library';

import { TenancyService } from '../../tenancy/tenancy.service.js';
import { NotificationEntity } from '../domain/notification.entity.js';
import type {
  FindForRecipientQuery,
  INotificationRepository,
  PagedNotifications,
  UpsertNotificationData,
} from '../domain/notification-repository.interface.js';

/** The subset of a persisted notification row this repository maps back to the domain entity. */
type NotificationRow = {
  id: string;
  organizationId: string;
  recipientUserId: string;
  kind: NotificationEntity['kind'];
  severity: NotificationEntity['severity'];
  dedupeKey: string;
  projectId: string | null;
  contractId: string | null;
  resourceType: string;
  resourceId: string;
  contextData: unknown;
  actionUrl: string | null;
  readAt: Date | null;
  resolvedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

@Injectable()
export class NotificationPrismaRepository implements INotificationRepository {
  constructor(private readonly tenancyService: TenancyService) {}

  async upsertByDedupeKey(data: UpsertNotificationData): Promise<void> {
    const prisma = this.tenancyService.getClient();
    const contextData = (data.contextData ?? undefined) as InputJsonValue | undefined;
    await prisma.notification.upsert({
      // Compound-unique input name generated by Prisma from the fields of
      // `notifications_org_recipient_dedupe_key` (verified against the generated client).
      where: {
        organizationId_recipientUserId_dedupeKey: {
          organizationId: data.organizationId,
          recipientUserId: data.recipientUserId,
          dedupeKey: data.dedupeKey,
        },
      },
      create: {
        organizationId: data.organizationId,
        recipientUserId: data.recipientUserId,
        kind: data.kind,
        severity: data.severity,
        dedupeKey: data.dedupeKey,
        projectId: data.projectId,
        contractId: data.contractId,
        resourceType: data.resourceType,
        resourceId: data.resourceId,
        contextData,
        actionUrl: data.actionUrl,
      },
      // Re-arm: a row that was auto-resolved and became live again clears its resolvedAt, and the
      // volatile fields (severity/context/actionUrl/kind) refresh to the current condition. readAt is
      // intentionally left alone — a user who read it once is not re-alerted for the same key.
      update: {
        kind: data.kind,
        severity: data.severity,
        contextData,
        actionUrl: data.actionUrl,
        resolvedAt: null,
      },
    });
  }

  async autoResolveMissing(
    organizationId: string,
    resourceType: string,
    liveDedupeKeys: string[],
  ): Promise<number> {
    const prisma = this.tenancyService.getClient();
    // Key on dedupeKey, not resourceId: a still-live resource whose key changed (a stage that slipped
    // DUE→OVERDUE, an invoice that aged into a new band) leaves its OLD key absent from
    // `liveDedupeKeys`, so its superseded row is closed here rather than stacking. Prisma treats
    // `notIn: []` as "match every row", so a source with nothing live closes all of its open rows.
    const result = await prisma.notification.updateMany({
      where: {
        organizationId,
        resourceType,
        resolvedAt: null,
        dedupeKey: { notIn: liveDedupeKeys },
      },
      data: { resolvedAt: new Date() },
    });
    return result.count;
  }

  async findForRecipientPaged(
    organizationId: string,
    recipientUserId: string,
    query: FindForRecipientQuery,
  ): Promise<PagedNotifications> {
    const prisma = this.tenancyService.getClient();
    const where = {
      organizationId,
      recipientUserId,
      resolvedAt: null,
      ...(query.unread ? { readAt: null } : {}),
    };
    const skip = (query.page - 1) * query.limit;
    const [rows, total] = await Promise.all([
      prisma.notification.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip,
        take: query.limit,
      }),
      prisma.notification.count({ where }),
    ]);
    return { items: rows.map((row) => this.toDomain(row)), total };
  }

  async countUnread(organizationId: string, recipientUserId: string): Promise<number> {
    const prisma = this.tenancyService.getClient();
    return prisma.notification.count({
      where: { organizationId, recipientUserId, resolvedAt: null, readAt: null },
    });
  }

  async markRead(
    organizationId: string,
    recipientUserId: string,
    notificationId: string,
  ): Promise<NotificationEntity | null> {
    const prisma = this.tenancyService.getClient();
    // Scope the update to the caller's own, un-resolved row. updateMany returns a count rather than
    // throwing, so a foreign or non-existent id resolves to `null` → 404 with no existence leak.
    const result = await prisma.notification.updateMany({
      where: { id: notificationId, organizationId, recipientUserId, resolvedAt: null },
      data: { readAt: new Date() },
    });
    if (result.count === 0) return null;
    const row = await prisma.notification.findFirst({
      where: { id: notificationId, organizationId, recipientUserId },
    });
    return row ? this.toDomain(row) : null;
  }

  async markAllRead(organizationId: string, recipientUserId: string): Promise<number> {
    const prisma = this.tenancyService.getClient();
    const result = await prisma.notification.updateMany({
      where: { organizationId, recipientUserId, resolvedAt: null, readAt: null },
      data: { readAt: new Date() },
    });
    return result.count;
  }

  private toDomain(row: NotificationRow): NotificationEntity {
    return new NotificationEntity(
      row.id,
      row.organizationId,
      row.recipientUserId,
      row.kind,
      row.severity,
      row.dedupeKey,
      row.projectId,
      row.contractId,
      row.resourceType,
      row.resourceId,
      (row.contextData ?? null) as Record<string, string | number> | null,
      row.actionUrl,
      row.readAt,
      row.resolvedAt,
      row.createdAt,
      row.updatedAt,
    );
  }
}
